apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: us-east1-docker.pkg.dev/todolister-b1fb8/todolister-repo/todoclient-gke:latest
          ports:
            - containerPort: 3000
