apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: us-east1-docker.pkg.dev/todolister-b1fb8/todolister-repo/todoserver-gke:latest
          ports:
            - containerPort: 5000
